apiVersion: v1
kind: Secret
metadata:
  name: appsecrets
type: Opaque
stringData: 
  MongoConfig__DatabaseName: $DatabaseName
  MongoConfig__User: $DatabaseUser
  MongoConfig__Password: $DatabasePassword
  Jwt__SecretKey: $JwtSecret
  Jwt__ExpiresIn: $JwtExpiresIn
  Jwt__RefreshTokenExpiresIn: $JwtRefreshExpiresIn
  Jwt__Issuer: $JwtIssuer
  Jwt__Audience: $JwtAudience
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg-identity-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eg-identity-management
  template:
    metadata:
      labels:
        app: eg-identity-management
    spec:
      containers:
      - image: inftfg2021/eg.identity.management:latest
        name: eg-identity-management
        env: 
          - name: ASPNETCORE_ENVIRONMENT
            value: $ENV
          - name: MongoConfig__DatabaseName
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: MongoConfig__DatabaseName
          - name: MongoConfig__User
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: MongoConfig__User
          - name: MongoConfig__Password
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: MongoConfig__Password
          - name: Jwt__SecretKey
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: Jwt__SecretKey
          - name: Jwt__ExpiresIn
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: Jwt__ExpiresIn
          - name: Jwt__RefreshTokenExpiresIn
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: Jwt__RefreshTokenExpiresIn
          - name: Jwt__Audience
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: Jwt__Audience
          - name: Jwt__Issuer
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: Jwt__Issuer
---
apiVersion: v1
kind: Service
metadata:
  name: eg-identity-management
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "eg-identity-management"
    port: 8081
  selector:
    app: eg-identity-management