name: Build and Deploy in Production Namespace

on: 
 push:
  branches:
  - main
    
env:
   tag: ${{ github.sha }} 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Verifying Docker Credentials
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
    
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/eg.identity.management:${{ env.tag }} -f ./deployment/Dockerfile .

    - name: Publish Docker Image
      run: |
        echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        docker push ${{ secrets.DOCKER_USER }}/eg.identity.management:${{ env.tag }}
    
    - name: Get Kube Config
      uses: okteto/actions/namespace@v1
      id: namespace
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: dev-tfg2021-escinf-una

    - name: Deploy Application to Okteto
      uses: okteto/actions/deploy@v1
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
      with:
        namespace: tfg2021-escinf-una
        manifest: ./deployment/prod-k8s.yml
        tag: ${{ secrets.DOCKER_USER }}/eg.identity.management:${{ env.tag }}
        waitOn: deployment/eg-identity-management
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag and update the repository
      - uses: actions/checkout@v2
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.tag }}
          message: "Latest release"